### ISSUE TITLE
Epic: Moderation tooling

### ISSUE THREAD

**Issue by strideynet** [strideynet/bsky-furry-feed#3]
- [x] https://github.com/strideynet/bsky-furry-feed/issues/8
- [ ] https://github.com/strideynet/bsky-furry-feed/issues/9
- [ ] https://github.com/strideynet/bsky-furry-feed/issues/10
